# Generated by Django 3.2.25 on 2025-07-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
