# Generated by Django 3.2.25 on 2025-08-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
