# Generated by Django 3.2.25 on 2025-08-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(default="A", max_length=250),
        ),
    ]
