# Generated by Django 3.2.25 on 2025-08-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0009_alter_task_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
